from config import settings


DEFAULT_FONT_FILE = settings.font_default


PRESETS = {
    "mp4_web_720p_small": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Lightweight web MP4 at 720p with faststart.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "-2:720",
            "video_preset": "veryfast",
            "crf": 23,
            "audio_bitrate": "128k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=-2:720",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "23",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_web_1080p": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Balanced 1080p web MP4 with faststart.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "-2:1080",
            "video_preset": "fast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=-2:1080",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_web_480p_tiny": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Tiny 480p preview MP4 with faststart.",
        "max_size_hint": "much smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "-2:480",
            "video_preset": "veryfast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=-2:480",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_vertical_1080x1920": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "9:16 vertical crop/scale for social platforms.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1920 (crop)",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_square_1080x1080": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "1:1 square crop/scale for social platforms.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1080 (crop)",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1080:force_original_aspect_ratio=increase,crop=1080:1080",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_vertical_1080x1920_safe_pad": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "9:16 vertical safe-frame with padding (no crop).",
        "expected_inputs": "Any aspect ratio video; adds padding to fit 1080x1920.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1920 (pad)",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1920:force_original_aspect_ratio=decrease,"
            "pad=1080:1920:(ow-iw)/2:(oh-ih)/2:color=black",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_vertical_720x1280": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Smaller 9:16 vertical crop/scale for social platforms.",
        "expected_inputs": "Any aspect ratio video; crops to 720x1280.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "720:1280 (crop)",
            "video_preset": "ultrafast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=720:1280:force_original_aspect_ratio=increase,crop=720:1280",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_vertical_720x1280_safe_pad": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "9:16 vertical safe-frame at 720x1280 with padding.",
        "expected_inputs": "Any aspect ratio video; pads to 720x1280.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "720:1280 (pad)",
            "video_preset": "ultrafast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=720:1280:force_original_aspect_ratio=decrease,"
            "pad=720:1280:(ow-iw)/2:(oh-ih)/2:color=black",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_square_720x720": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Smaller 1:1 square crop/scale for social platforms.",
        "expected_inputs": "Any aspect ratio video; crops to 720x720.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "720:720 (crop)",
            "video_preset": "ultrafast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=720:720:force_original_aspect_ratio=increase,crop=720:720",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_square_720x720_safe_pad": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "1:1 square safe-frame at 720x720 with padding.",
        "expected_inputs": "Any aspect ratio video; pads to 720x720.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "720:720 (pad)",
            "video_preset": "ultrafast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=720:720:force_original_aspect_ratio=decrease,"
            "pad=720:720:(ow-iw)/2:(oh-ih)/2:color=black",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_square_1080x1080_safe_pad": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "1:1 square safe-frame with padding (no crop).",
        "expected_inputs": "Any aspect ratio video; pads to 1080x1080.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1080 (pad)",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1080:force_original_aspect_ratio=decrease,"
            "pad=1080:1080:(ow-iw)/2:(oh-ih)/2:color=black",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_portrait_1080x1350": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "4:5 portrait crop/scale for social feeds.",
        "expected_inputs": "Any aspect ratio video; crops to 1080x1350.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1350 (crop)",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1350:force_original_aspect_ratio=increase,crop=1080:1350",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_portrait_720x900": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "4:5 portrait crop/scale at 720x900.",
        "expected_inputs": "Any aspect ratio video; crops to 720x900.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "720:900 (crop)",
            "video_preset": "ultrafast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=720:900:force_original_aspect_ratio=increase,crop=720:900",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_portrait_720x900_safe_pad": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "4:5 portrait safe-frame at 720x900 with padding.",
        "expected_inputs": "Any aspect ratio video; pads to 720x900.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "720:900 (pad)",
            "video_preset": "ultrafast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=720:900:force_original_aspect_ratio=decrease,"
            "pad=720:900:(ow-iw)/2:(oh-ih)/2:color=black",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_portrait_1080x1350_safe_pad": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "4:5 portrait safe-frame with padding (no crop).",
        "expected_inputs": "Any aspect ratio video; pads to 1080x1350.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1350 (pad)",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1350:force_original_aspect_ratio=decrease,"
            "pad=1080:1350:(ow-iw)/2:(oh-ih)/2:color=black",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_youtube_1920x1080": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "16:9 YouTube-ready 1080p with faststart.",
        "expected_inputs": "Any aspect ratio video; crops to 1920x1080.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1920:1080 (crop)",
            "video_preset": "fast",
            "crf": 21,
            "audio_bitrate": "192k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1920:1080:force_original_aspect_ratio=increase,crop=1920:1080",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-crf",
            "21",
            "-c:a",
            "aac",
            "-b:a",
            "192k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_youtube_1280x720": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "16:9 YouTube-ready 720p with faststart.",
        "expected_inputs": "Any aspect ratio video; crops to 1280x720.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1280:720 (crop)",
            "video_preset": "ultrafast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1280:720:force_original_aspect_ratio=increase,crop=1280:720",
            "-c:v",
            "libx264",
            "-preset",
            "ultrafast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_vertical_1080x1920_lower_third": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "9:16 vertical with a lower-third box + placeholder text.",
        "expected_inputs": "Any aspect ratio video; crops to 1080x1920.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1920 (crop)",
            "overlay": "lower third box + placeholder text",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            (
                "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,"
                "drawbox=x=0:y=ih*0.74:w=iw:h=ih*0.18:color=black@0.55:t=fill,"
                f"drawtext=fontfile={DEFAULT_FONT_FILE}:text=LOWER_THIRD:"
                "fontcolor=white:fontsize=64:x=(w-text_w)/2:y=h*0.78"
            ),
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_vertical_1080x1920_center_headline": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "9:16 vertical with centered headline placeholder.",
        "expected_inputs": "Any aspect ratio video; crops to 1080x1920.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1920 (crop)",
            "overlay": "center headline placeholder",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            (
                "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,"
                f"drawtext=fontfile={DEFAULT_FONT_FILE}:text=HEADLINE:"
                "fontcolor=white:fontsize=84:box=1:boxcolor=black@0.5:"
                "boxborderw=24:x=(w-text_w)/2:y=(h-text_h)/2"
            ),
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_vertical_1080x1920_top_banner_cta": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "9:16 vertical with a top banner CTA placeholder.",
        "expected_inputs": "Any aspect ratio video; crops to 1080x1920.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1920 (crop)",
            "overlay": "top banner box + placeholder text",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            (
                "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,"
                "drawbox=x=0:y=0:w=iw:h=ih*0.16:color=black@0.55:t=fill,"
                f"drawtext=fontfile={DEFAULT_FONT_FILE}:text=CTA:"
                "fontcolor=white:fontsize=64:x=(w-text_w)/2:y=h*0.04"
            ),
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp3_voice_128k": {
        "output_ext": ".mp3",
        "mime_type": "audio/mpeg",
        "output_container": "mp3",
        "purpose": "Voice-friendly MP3 at 128 kbps.",
        "max_size_hint": "smaller than source",
        "profile": {
            "audio_codec": "libmp3lame",
            "audio_bitrate": "128k",
        },
        "ffmpeg_args": [
            "-vn",
            "-c:a",
            "libmp3lame",
            "-b:a",
            "128k",
        ],
    },
    "mp3_voice_128k_loudnorm": {
        "output_ext": ".mp3",
        "mime_type": "audio/mpeg",
        "output_container": "mp3",
        "purpose": "Voice MP3 at 128 kbps with loudness normalization.",
        "expected_inputs": "Audio or video with audio; normalizes to ~-16 LUFS.",
        "max_size_hint": "smaller than source",
        "profile": {
            "audio_codec": "libmp3lame",
            "audio_bitrate": "128k",
            "audio_filter": "loudnorm (I=-16, LRA=11, TP=-1.5)",
        },
        "ffmpeg_args": [
            "-vn",
            "-af",
            "loudnorm=I=-16:LRA=11:TP=-1.5",
            "-c:a",
            "libmp3lame",
            "-b:a",
            "128k",
        ],
    },
    "mp4_social_reel_1080x1920_high": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Higher quality 9:16 social reel (1080x1920).",
        "max_size_hint": "larger than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1920 (crop)",
            "video_preset": "fast",
            "crf": 20,
            "audio_bitrate": "192k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-crf",
            "20",
            "-c:a",
            "aac",
            "-b:a",
            "192k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp3_voice_64k": {
        "output_ext": ".mp3",
        "mime_type": "audio/mpeg",
        "output_container": "mp3",
        "purpose": "Very small voice MP3 at 64 kbps.",
        "max_size_hint": "much smaller than source",
        "profile": {
            "audio_codec": "libmp3lame",
            "audio_bitrate": "64k",
        },
        "ffmpeg_args": [
            "-vn",
            "-c:a",
            "libmp3lame",
            "-b:a",
            "64k",
        ],
    },
    "mp3_voice_64k_loudnorm": {
        "output_ext": ".mp3",
        "mime_type": "audio/mpeg",
        "output_container": "mp3",
        "purpose": "Small voice MP3 at 64 kbps with loudness normalization.",
        "expected_inputs": "Audio or video with audio; normalizes to ~-16 LUFS.",
        "max_size_hint": "much smaller than source",
        "profile": {
            "audio_codec": "libmp3lame",
            "audio_bitrate": "64k",
            "audio_filter": "loudnorm (I=-16, LRA=11, TP=-1.5)",
        },
        "ffmpeg_args": [
            "-vn",
            "-af",
            "loudnorm=I=-16:LRA=11:TP=-1.5",
            "-c:a",
            "libmp3lame",
            "-b:a",
            "64k",
        ],
    },
    "m4a_voice_128k_loudnorm": {
        "output_ext": ".m4a",
        "mime_type": "audio/mp4",
        "output_container": "m4a",
        "purpose": "AAC M4A at 128 kbps with loudness normalization.",
        "expected_inputs": "Audio or video with audio; normalizes to ~-16 LUFS.",
        "max_size_hint": "smaller than source",
        "profile": {
            "audio_codec": "aac",
            "audio_bitrate": "128k",
            "audio_filter": "loudnorm (I=-16, LRA=11, TP=-1.5)",
        },
        "ffmpeg_args": [
            "-vn",
            "-af",
            "loudnorm=I=-16:LRA=11:TP=-1.5",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
        ],
    },
    "wav_pcm_16k_mono": {
        "output_ext": ".wav",
        "mime_type": "audio/wav",
        "output_container": "wav",
        "purpose": "ASR-friendly 16kHz mono WAV (PCM).",
        "max_size_hint": "larger than source",
        "profile": {
            "audio_codec": "pcm_s16le",
            "sample_rate_hz": 16000,
            "channels": 1,
        },
        "ffmpeg_args": [
            "-vn",
            "-ac",
            "1",
            "-ar",
            "16000",
            "-c:a",
            "pcm_s16le",
        ],
    },
    "wav_pcm_16k_mono_loudnorm": {
        "output_ext": ".wav",
        "mime_type": "audio/wav",
        "output_container": "wav",
        "purpose": "16kHz mono WAV (PCM) with loudness normalization.",
        "expected_inputs": "Audio or video with audio; normalizes to ~-16 LUFS.",
        "max_size_hint": "larger than source",
        "profile": {
            "audio_codec": "pcm_s16le",
            "sample_rate_hz": 16000,
            "channels": 1,
            "audio_filter": "loudnorm (I=-16, LRA=11, TP=-1.5)",
        },
        "ffmpeg_args": [
            "-vn",
            "-ac",
            "1",
            "-ar",
            "16000",
            "-af",
            "loudnorm=I=-16:LRA=11:TP=-1.5",
            "-c:a",
            "pcm_s16le",
        ],
    },
    "gif_preview_lowfps": {
        "output_ext": ".gif",
        "mime_type": "image/gif",
        "output_container": "gif",
        "purpose": "Low FPS GIF preview.",
        "max_size_hint": "small preview",
        "profile": {
            "fps": 8,
            "scale": "480:-2",
            "loop": 0,
        },
        "ffmpeg_args": [
            "-vf",
            "fps=8,scale=480:-2:flags=lanczos",
            "-loop",
            "0",
        ],
    },
}


def get_preset(name: str) -> dict:
    preset = PRESETS.get(name)
    if not preset:
        raise ValueError(f"Unknown preset: {name}")
    return preset


def describe_preset(name: str) -> dict:
    preset = get_preset(name)
    return {
        "name": name,
        "purpose": preset.get("purpose"),
        "expected_inputs": preset.get("expected_inputs"),
        "output_container": preset.get("output_container"),
        "mime_type": preset.get("mime_type"),
        "output_ext": preset.get("output_ext"),
        "profile": preset.get("profile", {}),
    }


def list_presets() -> list[dict]:
    items = []
    for name, preset in PRESETS.items():
        items.append(
            {
                "name": name,
                "purpose": preset.get("purpose"),
                "output_container": preset.get("output_container"),
                "max_size_hint": preset.get("max_size_hint"),
            }
        )
    return items


DRAFT_PRESET_MAP = {
    "mp4_social_vertical_1080x1920": "mp4_social_vertical_720x1280",
    "mp4_social_vertical_1080x1920_safe_pad": "mp4_social_vertical_720x1280_safe_pad",
    "mp4_social_square_1080x1080": "mp4_social_square_720x720",
    "mp4_social_square_1080x1080_safe_pad": "mp4_social_square_720x720_safe_pad",
    "mp4_social_portrait_1080x1350": "mp4_social_portrait_720x900",
    "mp4_social_portrait_1080x1350_safe_pad": "mp4_social_portrait_720x900_safe_pad",
    "mp4_youtube_1920x1080": "mp4_youtube_1280x720",
}


def draft_preset_for(name: str) -> str:
    return DRAFT_PRESET_MAP.get(name, name)


def map_presets_for_quality(presets: list[str], quality: str | None) -> list[str]:
    if quality and quality.strip().lower() == "draft":
        return [draft_preset_for(name) for name in presets]
    return list(presets)
