PRESETS = {
    "mp4_web_720p_small": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Lightweight web MP4 at 720p with faststart.",
        "max_size_hint": "smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "-2:720",
            "video_preset": "veryfast",
            "crf": 23,
            "audio_bitrate": "128k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=-2:720",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "23",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_web_1080p": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Balanced 1080p web MP4 with faststart.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "-2:1080",
            "video_preset": "fast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=-2:1080",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_web_480p_tiny": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Tiny 480p preview MP4 with faststart.",
        "max_size_hint": "much smaller than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "-2:480",
            "video_preset": "veryfast",
            "crf": 28,
            "audio_bitrate": "96k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=-2:480",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "28",
            "-c:a",
            "aac",
            "-b:a",
            "96k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_vertical_1080x1920": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "9:16 vertical crop/scale for social platforms.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1920 (crop)",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp4_social_square_1080x1080": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "1:1 square crop/scale for social platforms.",
        "max_size_hint": "similar to source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1080 (crop)",
            "video_preset": "veryfast",
            "crf": 22,
            "audio_bitrate": "160k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1080:force_original_aspect_ratio=increase,crop=1080:1080",
            "-c:v",
            "libx264",
            "-preset",
            "veryfast",
            "-crf",
            "22",
            "-c:a",
            "aac",
            "-b:a",
            "160k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp3_voice_128k": {
        "output_ext": ".mp3",
        "mime_type": "audio/mpeg",
        "output_container": "mp3",
        "purpose": "Voice-friendly MP3 at 128 kbps.",
        "max_size_hint": "smaller than source",
        "profile": {
            "audio_codec": "libmp3lame",
            "audio_bitrate": "128k",
        },
        "ffmpeg_args": [
            "-vn",
            "-c:a",
            "libmp3lame",
            "-b:a",
            "128k",
        ],
    },
    "mp4_social_reel_1080x1920_high": {
        "output_ext": ".mp4",
        "mime_type": "video/mp4",
        "output_container": "mp4",
        "purpose": "Higher quality 9:16 social reel (1080x1920).",
        "max_size_hint": "larger than source",
        "profile": {
            "video_codec": "libx264",
            "audio_codec": "aac",
            "scale": "1080:1920 (crop)",
            "video_preset": "fast",
            "crf": 20,
            "audio_bitrate": "192k",
            "faststart": True,
        },
        "ffmpeg_args": [
            "-vf",
            "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920",
            "-c:v",
            "libx264",
            "-preset",
            "fast",
            "-crf",
            "20",
            "-c:a",
            "aac",
            "-b:a",
            "192k",
            "-movflags",
            "+faststart",
        ],
    },
    "mp3_voice_64k": {
        "output_ext": ".mp3",
        "mime_type": "audio/mpeg",
        "output_container": "mp3",
        "purpose": "Very small voice MP3 at 64 kbps.",
        "max_size_hint": "much smaller than source",
        "profile": {
            "audio_codec": "libmp3lame",
            "audio_bitrate": "64k",
        },
        "ffmpeg_args": [
            "-vn",
            "-c:a",
            "libmp3lame",
            "-b:a",
            "64k",
        ],
    },
    "wav_pcm_16k_mono": {
        "output_ext": ".wav",
        "mime_type": "audio/wav",
        "output_container": "wav",
        "purpose": "ASR-friendly 16kHz mono WAV (PCM).",
        "max_size_hint": "larger than source",
        "profile": {
            "audio_codec": "pcm_s16le",
            "sample_rate_hz": 16000,
            "channels": 1,
        },
        "ffmpeg_args": [
            "-vn",
            "-ac",
            "1",
            "-ar",
            "16000",
            "-c:a",
            "pcm_s16le",
        ],
    },
    "gif_preview_lowfps": {
        "output_ext": ".gif",
        "mime_type": "image/gif",
        "output_container": "gif",
        "purpose": "Low FPS GIF preview.",
        "max_size_hint": "small preview",
        "profile": {
            "fps": 8,
            "scale": "480:-2",
            "loop": 0,
        },
        "ffmpeg_args": [
            "-vf",
            "fps=8,scale=480:-2:flags=lanczos",
            "-loop",
            "0",
        ],
    },
}


def get_preset(name: str) -> dict:
    preset = PRESETS.get(name)
    if not preset:
        raise ValueError(f"Unknown preset: {name}")
    return preset


def describe_preset(name: str) -> dict:
    preset = get_preset(name)
    return {
        "name": name,
        "purpose": preset.get("purpose"),
        "output_container": preset.get("output_container"),
        "mime_type": preset.get("mime_type"),
        "output_ext": preset.get("output_ext"),
        "profile": preset.get("profile", {}),
    }


def list_presets() -> list[dict]:
    items = []
    for name, preset in PRESETS.items():
        items.append(
            {
                "name": name,
                "purpose": preset.get("purpose"),
                "output_container": preset.get("output_container"),
                "max_size_hint": preset.get("max_size_hint"),
            }
        )
    return items
